version: '3.8'

services:
  web:
    build: .
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - PORT=${PORT}