# Generated by Django 5.2.5 on 2026-06-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('menu', 'menu'), ('close', 'close'), ('arrowRight', 'arrowRight'), ('arrowUpRight', 'arrowUpRight'), ('code', 'code'), ('globe', 'globe'), ('cloud', 'cloud'), ('server', 'server'), ('plug', 'plug'), ('wrench', 'wrench'), ('layers', 'layers'), ('bot', 'bot'), ('mic', 'mic'), ('chart', 'chart'), ('check', 'check'), ('mail', 'mail'), ('shield', 'shield'), ('zap', 'zap'), ('sparkles', 'sparkles'), ('database', 'database'), ('cube', 'cube'), ('star', 'star'), ('monitor', 'monitor'), ('lock', 'lock'), ('printer', 'printer'), ('refresh', 'refresh'), ('power', 'power'), ('upload', 'upload'), ('image', 'image'), ('grid', 'grid'), ('signal', 'signal'), ('leaf', 'leaf'), ('eye', 'eye'), ('wallet', 'wallet'), ('pin', 'pin'), ('clock', 'clock')], max_length=32)),
                ('title_en', models.CharField(max_length=120, verbose_name='Title (EN)')),
                ('title_ro', models.CharField(max_length=120, verbose_name='Title (RO)')),
                ('desc_en', models.TextField(verbose_name='Description (EN)')),
                ('desc_ro', models.TextField(verbose_name='Description (RO)')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers show first.')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide from the site without deleting.')),
                ('badge_en', models.CharField(blank=True, help_text='Small pill on the card, e.g. "RAG", "Voice".', max_length=40, verbose_name='Badge (EN)')),
                ('badge_ro', models.CharField(blank=True, max_length=40, verbose_name='Badge (RO)')),
            ],
            options={
                'verbose_name': 'AI Service',
                'verbose_name_plural': 'AI Services',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('menu', 'menu'), ('close', 'close'), ('arrowRight', 'arrowRight'), ('arrowUpRight', 'arrowUpRight'), ('code', 'code'), ('globe', 'globe'), ('cloud', 'cloud'), ('server', 'server'), ('plug', 'plug'), ('wrench', 'wrench'), ('layers', 'layers'), ('bot', 'bot'), ('mic', 'mic'), ('chart', 'chart'), ('check', 'check'), ('mail', 'mail'), ('shield', 'shield'), ('zap', 'zap'), ('sparkles', 'sparkles'), ('database', 'database'), ('cube', 'cube'), ('star', 'star'), ('monitor', 'monitor'), ('lock', 'lock'), ('printer', 'printer'), ('refresh', 'refresh'), ('power', 'power'), ('upload', 'upload'), ('image', 'image'), ('grid', 'grid'), ('signal', 'signal'), ('leaf', 'leaf'), ('eye', 'eye'), ('wallet', 'wallet'), ('pin', 'pin'), ('clock', 'clock')], max_length=32)),
                ('title_en', models.CharField(max_length=120, verbose_name='Title (EN)')),
                ('title_ro', models.CharField(max_length=120, verbose_name='Title (RO)')),
                ('desc_en', models.TextField(verbose_name='Description (EN)')),
                ('desc_ro', models.TextField(verbose_name='Description (RO)')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers show first.')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide from the site without deleting.')),
                ('category', models.CharField(choices=[('web', 'Web'), ('ai', 'AI'), ('cloud', 'Cloud'), ('software', 'Software')], help_text='Drives the "Our work" filter buttons.', max_length=20)),
                ('tag', models.CharField(help_text='Badge label on the card, e.g. "E-commerce", "WordPress".', max_length=40)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('menu', 'menu'), ('close', 'close'), ('arrowRight', 'arrowRight'), ('arrowUpRight', 'arrowUpRight'), ('code', 'code'), ('globe', 'globe'), ('cloud', 'cloud'), ('server', 'server'), ('plug', 'plug'), ('wrench', 'wrench'), ('layers', 'layers'), ('bot', 'bot'), ('mic', 'mic'), ('chart', 'chart'), ('check', 'check'), ('mail', 'mail'), ('shield', 'shield'), ('zap', 'zap'), ('sparkles', 'sparkles'), ('database', 'database'), ('cube', 'cube'), ('star', 'star'), ('monitor', 'monitor'), ('lock', 'lock'), ('printer', 'printer'), ('refresh', 'refresh'), ('power', 'power'), ('upload', 'upload'), ('image', 'image'), ('grid', 'grid'), ('signal', 'signal'), ('leaf', 'leaf'), ('eye', 'eye'), ('wallet', 'wallet'), ('pin', 'pin'), ('clock', 'clock')], max_length=32)),
                ('title_en', models.CharField(max_length=120, verbose_name='Title (EN)')),
                ('title_ro', models.CharField(max_length=120, verbose_name='Title (RO)')),
                ('desc_en', models.TextField(verbose_name='Description (EN)')),
                ('desc_ro', models.TextField(verbose_name='Description (RO)')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers show first.')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide from the site without deleting.')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
